### ISSUE TITLE
Quelea CI version 2026.0 : saving an edited db song removes it from the db

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#690]
I am running Quelea CI version 2026.0 (cross-platform) with the latest Azul Zulu 25 JDK FX:

openjdk version "25" 2025-09-16 LTS
OpenJDK Runtime Environment Zulu25.28+85-CA (build 25+36-LTS)
OpenJDK 64-Bit Server VM Zulu25.28+85-CA (build 25+36-LTS, mixed mode, sharing)

scenario: 1

- database_new contains existing song db created with an older Quelea version

scenario: 2

- database_new was empty created with CI version 2026.0 
- subsequent import of a .qsp file

In scen 1: saving an edited db song removes it from the db (see log below).
In scen 2: no error occurs

**Can this be fixed? (otherwise a conversion strategy would be needed for the users)**

--------------------

Oct 14, 2025 10:24:31 AM org.quelea.windows.main.MainWindow getSongEntryWindow
INFO: Creating song entry window
Oct 14, 2025 10:25:24 AM org.quelea.data.db.SongManager updateSong
WARNING: Error with database update, try to remove and add...
java.lang.IllegalStateException: Couldn't update database
        at org.quelea.data.db.HibernateUtil.execute(HibernateUtil.java:84)
        at org.quelea.data.db.SongManager.updateSong(SongManager.java:271)
        at org.quelea.data.db.SongManager.updateSong(SongManager.java:256)
        at org.quelea.services.utils.Utils$5.run(Utils.java:397)
        at org.quelea.services.utils.Utils$6$1.run(Utils.java:439)
Caused by: javax.persistence.EntityExistsException: A different object with the same identifier value was already associated with the session : [org.quelea.data.db.model.Theme#1]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:123)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1411)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:489)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3303)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2438)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:449)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
        at org.quelea.data.db.HibernateUtil.execute(HibernateUtil.java:78)
        ... 4 more

Oct 14, 2025 10:25:24 AM org.quelea.data.db.SongManager removeSongs
INFO: Removing songs [1]
Oct 14, 2025 10:25:26 AM org.quelea.data.db.SongManager removeSongs
INFO: Removed song [1]
Oct 14, 2025 10:25:26 AM org.quelea.data.db.SongManager updateSong
WARNING: Try to add...
java.lang.IllegalStateException: Couldn't update database
        at org.quelea.data.db.HibernateUtil.execute(HibernateUtil.java:84)
        at org.quelea.data.db.SongManager.updateSong(SongManager.java:271)
        at org.quelea.data.db.SongManager.updateSong(SongManager.java:256)
        at org.quelea.services.utils.Utils$5.run(Utils.java:397)
        at org.quelea.services.utils.Utils$6$1.run(Utils.java:439)
Caused by: javax.persistence.EntityExistsException: A different object with the same identifier value was already associated with the session : [org.quelea.data.db.model.Theme#1]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:123)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1411)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:489)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3303)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2438)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:449)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
        at org.quelea.data.db.HibernateUtil.execute(HibernateUtil.java:78)
        ... 4 more

ERROR SqlExceptionHelper integrity constraint violation: unique constraint or index violation; SYS_PK_10098 table: TEXTSHADOW
Oct 14, 2025 10:25:26 AM org.quelea.data.db.SongManager addSong
WARNING: Couldn't add song
java.lang.IllegalStateException: Couldn't update database
        at org.quelea.data.db.HibernateUtil.execute(HibernateUtil.java:84)
        at org.quelea.data.db.SongManager.addSong(SongManager.java:219)
        at org.quelea.data.db.SongManager.addSong(SongManager.java:190)
        at org.quelea.data.db.SongManager.updateSong(SongManager.java:301)
        at org.quelea.data.db.SongManager.updateSong(SongManager.java:256)
        at org.quelea.services.utils.Utils$5.run(Utils.java:397)
        at org.quelea.services.utils.Utils$6$1.run(Utils.java:439)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1411)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:489)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3303)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2438)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:449)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
        at org.quelea.data.db.HibernateUtil.execute(HibernateUtil.java:78)
        ... 6 more
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:59)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
        at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3375)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3937)
        at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:107)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
        at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:987)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1407)
        ... 15 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation; SYS_PK_10098 table: TEXTSHADOW
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
        ... 27 more
Caused by: org.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation; SYS_PK_10098 table: TEXTSHADOW
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.Constraint.getException(Unknown Source)
        at org.hsqldb.index.IndexAVL.insert(Unknown Source)
        at org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source)
        at org.hsqldb.TransactionManager2PL.addInsertAction(Unknown Source)
        at org.hsqldb.Session.addInsertAction(Unknown Source)
        at org.hsqldb.Table.insertSingleRow(Unknown Source)
        at org.hsqldb.StatementDML.insertSingleRow(Unknown Source)
        at org.hsqldb.StatementInsert.getResult(Unknown Source)
        at org.hsqldb.StatementDMQL.execute(Unknown Source)
        at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
        at org.hsqldb.Session.execute(Unknown Source)
        ... 30 more

Oct 14, 2025 10:25:27 AM org.quelea.data.db.SongManager getSongs
INFO: Adding 3,511 songs to index

**Comment by berry120** [comment]
Good spot! This should now be fixed - if you could confirm that'd be awesome.

**Comment by mrpenguinb** [comment]
Still an issue for me in the latest CI release. Or has it not been added to the CI releases yet?

**Comment by berry120** [comment]
No, this should be fixed - do you get the same issue with the same stack
trace above?

Thanks,

Michael

**Comment by mrpenguinb** [comment]
> Are you using the latest CI installer version on W11 as well? Or perhaps a previous one?

The latest, downloaded and installed. Still presents itself.
